### PR TITLE
feature: add hero section to homepage

### PR DESCRIPTION
**Pull request by Xand6r**
### Explainer
https://www.loom.com/share/1e8822d36b664fa682e07a44dd0e8bd3

### Desktop
image

### Mobile
image

### CODE REVIEW

**Comment by rajashree23** [comment]
@Xand6r, I have a few questions-

1. For margin, padding and font size isn't it better to go with rem?
2. Does @include mobile-breakpoint sets the responsiveness for the mobile layout? If yes, can you please explain it to me?
3. Considering @include mobile-breakpoint is for the mobile viewport, why are we using px values? Wouldn't it overwrite the user's default settings?

**Comment by Xand6r** [comment]
> @Xand6r, I have a few questions-
> 
> 1. For margin, padding and font size isn't it better to go with rem?
> 2. Does @include mobile-breakpoint sets the responsiveness for the mobile layout? If yes, can you please explain it to me?
> 3. Considering @include mobile-breakpoint is for the mobile viewport, why are we using px values? Wouldn't it overwrite the user's default settings?

1) The main problem in responsive design is making sure all of the scales of the items are maintained if I were to use rem for font size, margin and padding while using VW for width and height. we would have a weird situation where the scale becomes distorted. the idea is to have the site look exactly the same across all screen sizes. so we have to be consistent in the uint we use. Also as opposed to using rem instead of vw, i actually battled with that choice lol, we could use rem all through but it doesn't ensure that the scale remains the same across all sizes, it just ensures that our measurements are relative to the base font size, but on a larger screen things would get distorted.
take a look at this, this is for a large screen, and notice there are some inconsistencies.
image

So we could switch to rem for desktop, then make the base size 0.8vw which is equal to (16/1922) i.e a 16px on a 1922 screen. but that just makes the calculations complicated.  so its more straightforward to use VW on desktop view in our case.
But for mobile, we could switch to rem sure for the user settings.

**Comment by Xand6r** [comment]
> @Xand6r, I have a few questions-
> 
> 1. For margin, padding and font size isn't it better to go with rem?
> 2. Does @include mobile-breakpoint sets the responsiveness for the mobile layout? If yes, can you please explain it to me?
> 3. Considering @include mobile-breakpoint is for the mobile viewport, why are we using px values? Wouldn't it overwrite the user's default settings?

2) @include mobile-breakpoint is a mixin, instead of writing media queries everywhere, i wrote the media query as a mixin
here's the code
```
@mixin mobile-breakpoint {
  @media (max-width: $mobile-breakpoint ){
    @content;
  }
}

@mixin tab-breakpoint {
  @media (max-width: $tab-breakpoint ){
    @content;
  }
}

```
and we use the mixin as below:
```
    @include mobile-breakpoint() {
      top: 65px;
    }
```
so this essentially passes on whatever property defined in the mixin into the media query as below, and the final effect is
```
  @media (max-width: $mobile-breakpoint ){
    top: 65px;
  }
```
so this way the media queries are more abstracted and standardized throughout the entire application.
if you don't understand, i could create a video explaining it or we could get on a call.

**Comment by Xand6r** [comment]
> @Xand6r, I have a few questions-
> 
> 1. For margin, padding and font size isn't it better to go with rem?
> 2. Does @include mobile-breakpoint sets the responsiveness for the mobile layout? If yes, can you please explain it to me?
> 3. Considering @include mobile-breakpoint is for the mobile viewport, why are we using px values? Wouldn't it overwrite the user's default settings?

3) Yes for mobile we could switch to using rem, you're right so as not to overwrite the user's default settings. we could create an issue for it.

**Comment by rajashree23** [comment]
> @mixin mobile-breakpoint

Got it, thanks

**Comment by rajashree23** [comment]
> > @Xand6r, I have a few questions-
> > 
> > 1. For margin, padding and font size isn't it better to go with rem?
> > 2. Does @include mobile-breakpoint sets the responsiveness for the mobile layout? If yes, can you please explain it to me?
> > 3. Considering @include mobile-breakpoint is for the mobile viewport, why are we using px values? Wouldn't it overwrite the user's default settings?
> 
> 3. Yes for mobile we could switch to using rem, you're right so as not to overwrite the user's default settings.  using the vs code extension i mentioned in the video, we can easily convert it to rem. we could create an issue for it.

absolutely, that extension is a saviour. I created the issue here- https://github.com/ChainWhiZ/chainwhiz-dapp-v2/issues/23

**Pull request merged**
